"""add funding opportunities table

Revision ID: 4df7c98abf3b
Revises: da9589749300
Create Date: 2026-09-14 03:37:54.258236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df7c98abf3b'
down_revision: Union[str, None] = 'da9589749300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('eligible_project_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('eligible_countries', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('eligible_stages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('min_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('amount_label', sa.String(length=255), nullable=False),
    sa.Column('application_info', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_opportunities')
    # ### end Alembic commands ###
