"""add subscription plans and AI credit usage

Revision ID: 83c81138106b
Revises: a41ce01fb665
Create Date: 2026-09-14 04:18:57.057424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c81138106b'
down_revision: Union[str, None] = 'a41ce01fb665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_credit_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_credit_usage_user_id'), 'ai_credit_usage', ['user_id'], unique=False)
    # The ENUM type must exist before it can be used in ADD COLUMN — unlike
    # CREATE TABLE, Alembic doesn't create it implicitly here.
    subscription_plan = sa.Enum('FREE', 'PRO', 'STUDIO', name='subscription_plan')
    subscription_plan.create(op.get_bind(), checkfirst=True)
    # server_default lets this ADD COLUMN succeed on a table that already
    # has rows (existing users default to FREE); dropped right after so
    # the ORM-level Python default is the only one going forward.
    op.add_column(
        'users',
        sa.Column('plan', subscription_plan, nullable=False, server_default='FREE'),
    )
    op.alter_column('users', 'plan', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.drop_index(op.f('ix_ai_credit_usage_user_id'), table_name='ai_credit_usage')
    op.drop_table('ai_credit_usage')
    # ### end Alembic commands ###
    sa.Enum(name='subscription_plan').drop(op.get_bind(), checkfirst=True)
