"""initial schema: users and projects

Revision ID: e9e4dd6b8732
Revises: 
Create Date: 2026-09-13 23:31:32.946230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e4dd6b8732'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=True),
    sa.Column('prenom', sa.String(length=120), nullable=True),
    sa.Column('pays', sa.String(length=120), nullable=True),
    sa.Column('ville', sa.String(length=120), nullable=True),
    sa.Column('profession', sa.String(length=120), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('user_type', sa.Enum('AUTHOR', 'DIRECTOR', 'PRODUCER', 'INSTITUTION', 'ADMIN', name='user_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.Enum('DOCUMENTARY', 'FEATURE_FILM', 'SHORT_FILM', 'TV_SERIES', 'WEB_SERIES', 'FICTION', 'ANIMATION', name='project_type'), nullable=False),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('logline', sa.Text(), nullable=True),
    sa.Column('short_synopsis', sa.Text(), nullable=True),
    sa.Column('long_synopsis', sa.Text(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('IDEA', 'DEVELOPMENT', 'WRITING', 'PRE_PRODUCTION', 'PRODUCTION', 'POST_PRODUCTION', 'COMPLETED', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Postgres ENUM types are independent objects and are NOT dropped
    # automatically when the tables that use them are dropped — without
    # this, re-running upgrade after a downgrade fails with
    # "type ... already exists". Not auto-generated by `alembic revision
    # --autogenerate`; added manually.
    sa.Enum(name='project_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='project_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_type').drop(op.get_bind(), checkfirst=True)
